# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Deploy Package

on:
  workflow_dispatch:
    inputs:
      deploy-package:
        description: 'Deploy package'
        required: true
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: >
          [
            {
              "id": "central",
              "url": "https://repo1.maven.org/maven2"             
            },
            {
              "id": "github",
              "url": "https://maven.pkg.github.com/acolad-digital/com.acolad.imagemap-pdf",
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
        servers: >
          [
            {
              "id": "github",
              "username": "Nico-Amplexor",
              "password": "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"              
            }
          ]
    - if: github.event.inputs.deploy-package == 'true'    
      name: Deploy with Maven    
      run: mvn -B package deploy --file pom.xml
    - if: github.event.inputs.deploy-package != 'true'      
      name: Build only, with Maven    
      run: mvn -B package --file pom.xml  
